[project]
name = "speech-to-text-api"
version = "0.1.0"
description = "ASR by OpenAI API"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi>=0.133.0",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.22",
    "torchaudio==2.8.0",
    "torchvision==0.23.0",
    "uvicorn>=0.41.0",
    # "ctranslate2",
    # "numpy==1.26.4",
    # "torch==2.8.0",
    # "torchvision==0.23.0",
    "whisperx",
    # "onnxruntime<1.24.1",
    # "pydantic>=2.11.7",
    # "python-dotenv>=1.1.1",
    # "fastapi>=0.128.7",
    # "pydantic>=2.12.5",
    # "python-dotenv>=1.2.1",
    # "python-multipart>=0.0.22",
    # "requests>=2.32.5",
    # "uvicorn>=0.40.0",
]

# [tool.uv.sources]
# ctranslate2 = { path = "packages/ctranslate2-4.4.0-cp310-cp310-manylinux_2_35_aarch64.whl" }
# torch = { index = "jetson-jp6-cu126" }
# 
# [[tool.uv.index]]
# name = "jetson-jp6-cu126"
# url = "https://pypi.jetson-ai-lab.io/jp6/cu126"
# explicit = true
